services:
  azan_cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azan_cron_container
    volumes:
      - ./prayer_data:/app/prayer_data
      - ./mp3:/app/mp3
    environment:
      - TZ=Asia/Kuala_Lumpur
    restart: always
    devices:
      - "/dev/snd:/dev/snd"  # Access to sound device

